id = "superior-green-theme"
name = "Superior Green"
schema_version = 1
version = "0.0.10"
authors = ["rm_reins"]
description = "Everyone knows that green is the best color."
repository = "https://github.com/rm-reins/Superior-Green"
themes = ["themes/superior-green.json", "themes/superior-green-no-italics.json"]
